### ISSUE TITLE
Modify 'separator' output character

### ISSUE THREAD

**Issue by cantide** [gerhard/glz_custom_fields_public#10]
In the plugin options: a simple field to change the character (currently the | character) used for separating a list of values from a custom field.

**Comment by gerhard** [comment]
Don't forget to vote for your feature request, otherwise it will be right at the bottom and could take forever to get it done.

**Comment by gerhard** [comment]
This is identical to the "configure delimiter" task. I'll close this since that task is already planned for the next release.
