### ISSUE TITLE
Only word characters allowed

### ISSUE THREAD

**Issue by mlarino** [gerhard/glz_custom_fields_public#17]
Only word Characters are allowed, why not create a space to name those custom fields and show those names in the write tab?

Right now I need a custom fields names like:
Surface (m2)
Price/month
Etc…

And is not possible.

**Comment by gerhard** [comment]
Already planned for v1.2.5, thanks for raising this ; ).

**Comment by gerhard** [comment]
Duplicate, see http://github.com/gerhard/glz_custom_fields_public/issues#issue/18
