### ISSUE TITLE
Populate custom field values with PHP script

### ISSUE THREAD

**Issue by gerhard** [gerhard/glz_custom_fields_public#2]
Enable users to run their own PHP scripts and populate values for custom fields. This is trigger words functionality taken to the next level. These are the default scripts which will be provided:
- all image categories
- all file categories
- all article categories (parent-child formatting)

There will be an example which will include how to fetch values based on various criteria. It's plain SQL so it should be pretty straightforward for most. As long as the script result adheres to the interface, anything can be passed into those values.

**Comment by redbotxx** [comment]
This would really bring textpattern to the next level. For example I could use a multiselect containing all files (for easy association with an article) or a select containing all sections (for fake subsections) or even a select which gets values generated by another custom field (this time a text input)... the possibilities are endless!
P.S. I noticed the voting system was acting strangely the other day, adding a -1 insted of a +1 (one "-1" is mine, sorry. Of course I meant +1)

**Comment by gerhard** [comment]
Yes, indeed, this seems really exciting stuff, can hardly wait to get down and code the thing.

No idea why the voting system is playing up. What I do know though is that this is going to be one of the first features to be developed since it has the most votes : ).
