### ISSUE TITLE
Configure custom field visibility based on section

### ISSUE THREAD

**Issue by gerhard** [gerhard/glz_custom_fields_public#3]
This is sed_section_fields functionality incorporated in this plugin. Rather than defining which custom fields are shown on a per section basis, do it the other way round: select which sections should the custom field be displayed on.

**Comment by whaleen** [comment]
sed_section_fields works fine for me but the ability to multi-select the section(s) for a custom field  when creating it would be great. A _select all_ would be handy for some I'd imagine.

**Comment by gerhard** [comment]
I'm imagining a custom field to be visible across all sections by default. All sections will be a list of checkboxes with a "select all" option. That's a standard approach really, anything beyond that would be over-engineering me thinks.

**Comment by whaleen** [comment]
Sounds good. Once sed_section_fields functionality is built in I expect you'll get the whole subscriber base offering their ideas so at that point it may be easier to see what the demands are. At the risk of 'over-engineering' we might use further preferences so site managers can adjust per their workflow. An "all section on/off by default choice" might be useful. The only other valuable thing I can think of is a choice to isolate a selection of sections that should be ignored completely. So, those two preferences would be very useful to me. I should point out that these things are really nit picky so ignore them if you like. :) I can get along fine.

**Comment by gerhard** [comment]
I'll get the basic stuff done first, if I get some more time, I'll look into the nit-picky ones as well : ). The devil is in the details, or so they say...

**Comment by Gil-Goldshlager** [comment]
You can hide custom fields based on section with the "bot_write_tab_customize" plugin.

**Comment by gerhard** [comment]
That is great Gil, thanks for the tip!

Thanks to Luca and his marvelous plugin, I no longer need to write this functionality, his plugin already provides it and much much more.

Check out [bot_write_tab_customize](http://textpattern.org/plugins/1134/bot_write_tab_customize).

**Comment by gerhard** [comment]
I am closing this issue now, check the above comment for more info.
