### ISSUE TITLE
Configure glz_custom_fields link not working when in subdirectory

### ISSUE THREAD

**Issue by testdept** [gerhard/glz_custom_fields_public#32]
My test Txp site resides in a subdirectory therefore the link to 'Configure glz_custom_fields', available on the admin page is not working properly (directs to site without subdir).

I resolved this by editing the file glz_custom_fields.js, line 147,
adding '+window.location.pathname' to 'window.location.host' and omitting '/textpattern'.

Works for now but I haven't tested my adaptation on a site where Txp does not reside in a subdirectory...

original
`$("select#custom_set_type").after("<span class=\"right\"><em><a href=\"http://"+window.location.host+"/textpattern?event=plugin_prefs.glz_custom_fields\">Configure glz_custom_fields</a></em></span>");`
adapted to
`$("select#custom_set_type").after("<span class=\"right\"><em><a href=\"http://"+window.location.host+window.location.pathname+"?event=plugin_prefs.glz_custom_fields\">Configure glz_custom_fields</a></em></span>");`

**Comment by gerhard** [comment]
Excellent, thanks so much! Already added original file.
