### ISSUE TITLE
Inline help

### ISSUE THREAD

**Issue by gerhard** [gerhard/glz_custom_fields_public#6]
Provide help support for custom fields. Admin might want to provide extra information for custom fields, maybe a specific format to adhere to or explain what the custom field is for. There are plenty of jQuery tooltip plugins, pick one and DO IT.

**Comment by redbotxx** [comment]
Hi Gerhard,
FYI there is already a txp [plugin](http://forum.textpattern.com/viewtopic.php?id=31951) (written by me, incidentally) which does exactly this, not only for custom fields but for almost every item in textpattern admin.

**Comment by gerhard** [comment]
That's great Luca, thanks for the tip!

**Comment by whaleen** [comment]
[bot_admin_tooltips](http://forum.textpattern.com/viewtopic.php?id=31951) is excellent. No need to roll what it does into glz_custom_fields, in my opinion.

**Comment by gerhard** [comment]
Another excellent suggestion Josh. I'm closing this ticket and adding your tip to the wiki.
